version: '3'
services:
  es-container:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    command: Xvfb +extension GLX +render -noreset
    #--device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - ../../../endless-sky:/workspace/endless-sky
      - .:/workspace/endless-sky/.devcontainer
      - ../.vscode:/workspace/endless-sky/.vscode
    environment:
      DISPLAY: ':99'
