version: '3'
services:
  es-container:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/bash -c 'while sleep 1000;do true;done'
    #--device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined
    devices:
      - /dev/dri
      - /dev/fuse
      - /dev/snd
    cap_add:
      - SYS_ADMIN
    security_opt:
      - 'apparmor:unconfined'
    volumes:
      - ../../../endless-sky:/workspace/endless-sky
      - ../.vscode:/workspace/endless-sky/.vscode
      - .:/workspace/endless-sky/.devcontainer
      - ./clang-format:/workspace/endless-sky/.clang-format
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: $DISPLAY
